name: demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to' # A short description of the parameter
        required: true                         # Whether this parameter is mandatory
        type: choice                           # Specifies that this is a dropdown
        options:                               # Defines the options for the dropdown
          - development
          - staging
          - production
        default: production   
         
  
jobs:
  build:
    runs-on: ubuntu-20.04 
    
    env:
      env_prod : " prod "
    

    steps:
      - name: run a job
        run: echo successful ${{ env.env_prod}}
      - name: Define and use my_test variable
        run: |
          sindhu="settlement_racha"
          echo "The value of sindhu is  $sindhu"  # Use the variable
      - name: Display GitHub context variables
        run: |
          echo "Triggered by: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Ref: ${{ github.ref }}"   

    
  
    
