name: demo

on:
  push:
    branches: [ main ]
  #workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04 
    
    env:
      env_prod = " prod "
    

    steps:
      - name: run a job
        run: echo successful ${{ env.env_prod }}
      - name: Define and use my_test variable
        run: |
          my_test="testing"  # Define the variable
          echo "The value of my_test is $my_test {{steps.job_id.outputs.result}}"  # Use the variable

    
  
    
