name: demo

on:
  push:
    branches: [ main ]
  #workflow_dispatch:
    env:
      env_prod = prod
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: run a job
        My_var = testing        
        run: echo successful {{$env.env_prod}} & {{$My_var}} {{$github.jobid}}

    
  
    
