name: demo

on:
  push:
    branches: [ main ]
  #workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04 
    
    env:
      env_prod : " prod "
    

    steps:
      - name: run a job
        run: echo successful ${{ env.env_prod }}
      - name: Define and use my_test variable
        run: |
          sindhu ="settlement_racha"
          echo "The value of my_test is $my_test $sindhu"  # Use the variable
      - name: Display GitHub context variables
        run: |
          echo "Triggered by: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Ref: ${{ github.ref }}"   

    
  
    
