name: demo

on:
  push:
    branches: [ main ]
  #workflow_dispatch:
    env:
      env_prod = prod
    var: 
      var_prod = testing_prod
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: run a job
        run: echo successful {{$env.env_prod}} & {{var.var_prod}}

    
  
    
