name: demo

on:
  push:
    branches: [ main ]
  #workflow_dispatch:
    env:
      env_prod = prod
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: run a job
        run: echo successful {{$env.env_prod}} 
      - name: Define and use my_test variable
        run: |
          my_test="testing"  # Define the variable
          echo "The value of my_test is $my_test {{github.job.jobid}}"  # Use the variable

    
  
    
