name: demo

on:
  #push:
    branches: [ main ]
  #workflow_dispatch:
env = test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run a job
        run: echo successful {{$env}}

    
  
    
